# DO NOT COMMIT THIS FILE
apiVersion: v1
kind: Secret
metadata:
  name: vault-secret
  namespace: #namespace as mentioned in the values.yaml
type: Opaque
stringData:
  root-token: #your-vault-root-token